boot.o: boot.S multiboot.h x86_desc.h types.h
handler_wrappers.o: handler_wrappers.S keyboard.h types.h rtc.h pit.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h lib.h syscall.h \
  keyboard.h rtc.h i8259.h terminal.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_init.o: idt_init.c x86_desc.h types.h idt_init.h lib.h keyboard.h \
  rtc.h handler_wrappers.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  idt_init.h paging.h keyboard.h rtc.h filesystem.h terminal.h syscall.h \
  pit.h scheduler.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h terminal.h \
  syscall.h rtc.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
pit.o: pit.c pit.h types.h paging.h x86_desc.h i8259.h filesystem.h \
  keyboard.h rtc.h lib.h terminal.h scheduler.h syscall.h
rtc.o: rtc.c rtc.h types.h terminal.h i8259.h lib.h
scheduler.o: scheduler.c scheduler.h types.h paging.h x86_desc.h i8259.h \
  filesystem.h keyboard.h rtc.h lib.h terminal.h pit.h syscall.h
syscall.o: syscall.c syscall.h keyboard.h types.h rtc.h i8259.h lib.h \
  terminal.h paging.h filesystem.h x86_desc.h
terminal.o: terminal.c terminal.h types.h lib.h paging.h
